#!/bin/sh
set -eu

soft_run=
while getopts "s" opt; do
    case "$opt" in
        s)  soft_run=1
    esac
done

# Move to the repo that this script resides in
cd "$(dirname "$0")"
pwd

# Generate and extract metadata needed
year="$(date +"%Y")"
uuid="$(julia -e "using UUIDs; print(UUIDs.uuid4())")"
name="$(git config user.name)"
email="$(git config user.email)"

# Use metadata to generate customized project files
sed -e "s/<year>/$year/g" \
    -e "s/<uuid>/$uuid/g" \
    -e "s/<name>/$name/g" \
    -e "s/<email>/$email/g" \
    Project.toml.template > Project.toml

if [ -z "$soft_run" ]; then
    git rm Project.toml.template
fi

sed -e "s/<year>/$year/g" \
    "src/AdventOfCode<year>.jl" > "src/AdventOfCode$year.jl"

if [ -z "$soft_run" ]; then
    git rm "src/AdventOfCode<year>.jl"
fi

# Remove the script itself
if [ -z "$soft_run" ]; then
    git rm generate-new-year --cached
fi
